### ISSUE TITLE
character model wrong

### ISSUE THREAD

**Issue by ldincredible** [EasternJournalist/live_mocap#1]
Hi, I'd like to try this code，but I got this error. I ran the export_skeleton script and found that bone_remap was none, maybe the character model wasn't adjusted properly, but I'm not familiar with using blender. How should I adjust the character model, or can you send me a character model? 

Export skeleton...
Blender 3.2.0 (hash e05e1e369187 built 2022-06-08 11:13:18)
Read prefs: C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend
Read blend: E:\3Dpose\test_data\characters\hutao.blend
bone_matrix_rel float32 (25, 4, 4) True
bone_matrix_world float32 (25, 4, 4) True
INFO: Created TensorFlow Lite XNNPACK delegate for CPU.
Traceback (most recent call last):
  File "mocap.py", line 125, in <module>
    main()
  File "mocap.py", line 60, in main
    skeleton_ik_solver = SkeletonIKSolver(
  File "E:\3Dpose\live_mocap\skeleton_ik_solver.py", line 95, in __init__
    self.joint_pairs_a, self.joint_pairs_b = joint_pairs_id[:, 0], joint_pairs_id[:, 1]
IndexError: too many indices for tensor of dimension 1

`{
    "bone_names": [
        "Pelvis",
        "Spine1",
        "Spine2",
        "Spine3",
        "Neck",
        "Head",
        "mixamorig:HeadTop_End",
        "L_Collar",
        "L_Shoulder",
        "L_Elbow",
        "L_Wrist",
        "R_Collar",
        "R_Shoulder",
        "R_Elbow",
        "R_Wrist",
        "L_Hip",
        "L_Knee",
        "L_Ankle",
        "L_Foot",
        "mixamorig:LeftToe_End",
        "R_Hip",
        "R_Knee",
        "R_Ankle",
        "R_Foot",
        "mixamorig:RightToe_End"
    ],
    "bone_parents": {
        "Pelvis": null,
        "Spine1": "Pelvis",
        "Spine2": "Spine1",
        "Spine3": "Spine2",
        "Neck": "Spine3",
        "Head": "Neck",
        "mixamorig:HeadTop_End": "Head",
        "L_Collar": "Spine3",
        "L_Shoulder": "L_Collar",
        "L_Elbow": "L_Shoulder",
        "L_Wrist": "L_Elbow",
        "R_Collar": "Spine3",
        "R_Shoulder": "R_Collar",
        "R_Elbow": "R_Shoulder",
        "R_Wrist": "R_Elbow",
        "L_Hip": "Pelvis",
        "L_Knee": "L_Hip",
        "L_Ankle": "L_Knee",
        "L_Foot": "L_Ankle",
        "mixamorig:LeftToe_End": "L_Foot",
        "R_Hip": "Pelvis",
        "R_Knee": "R_Hip",
        "R_Ankle": "R_Knee",
        "R_Foot": "R_Ankle",
        "mixamorig:RightToe_End": "R_Foot"
    },
    "bone_matrix_rel": "bone_matrix_rel.npy",
    "bone_matrix_world": "bone_matrix_world.npy",
    "bone_remap": {
        "left_ear": null,
        "right_ear": null,
        "left_eye": null,
        "right_eye": null,
        "head": null,
        "neck": null,
        "left_collar": null,
        "right_collar": null,
        "left_shoulder": null,
        "right_shoulder": null,
        "left_elbow": null,
        "right_elbow": null,
        "left_wrist": null,
        "right_wrist": null,
        "spine1": null,
        "spine2": null,
        "spine3": null,
        "pelvis": null,
        "left_hip": null,
        "right_hip": null,
        "left_knee": null,
        "right_knee": null,
        "left_ankle": null,
        "right_ankle": null,
        "left_toe": null,
        "right_toe": null,
        "left_index1": null,
        "left_index2": null,
        "left_index3": null,
        "left_index4": null,
        "left_middle1": null,
        "left_middle2": null,
        "left_middle3": null,
        "left_middle4": null,
        "left_ring1": null,
        "left_ring2": null,
        "left_ring3": null,
        "left_ring4": null,
        "left_pinky1": null,
        "left_pinky2": null,
        "left_pinky3": null,
        "left_pinky4": null,
        "left_thumb1": null,
        "left_thumb2": null,
        "left_thumb3": null,
        "left_thumb4": null,
        "right_index1": null,
        "right_index2": null,
        "right_index3": null,
        "right_index4": null,
        "right_middle1": null,
        "right_middle2": null,
        "right_middle3": null,
        "right_middle4": null,
        "right_ring1": null,
        "right_ring2": null,
        "right_ring3": null,
        "right_ring4": null,
        "right_pinky1": null,
        "right_pinky2": null,
        "right_pinky3": null,
        "right_pinky4": null,
        "right_thumb1": null,
        "right_thumb2": null,
        "right_thumb3": null,
        "right_thumb4": null
    }
}`

**Comment by EasternJournalist** [comment]
> Hi, I'd like to try this code，but I got this error. I ran the export_skeleton script and found that bone_remap was none, maybe the character model wasn't adjusted properly, but I'm not familiar with using blender. How should I adjust the character model, or can you send me a character model?
> 
> Export skeleton... Blender 3.2.0 (hash e05e1e369187 built 2022-06-08 11:13:18) Read prefs: C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend Read blend: E:\3Dpose\test_data\characters\hutao.blend bone_matrix_rel float32 (25, 4, 4) True bone_matrix_world float32 (25, 4, 4) True INFO: Created TensorFlow Lite XNNPACK delegate for CPU. Traceback (most recent call last): File "mocap.py", line 125, in main() File "mocap.py", line 60, in main skeleton_ik_solver = SkeletonIKSolver( File "E:\3Dpose\live_mocap\skeleton_ik_solver.py", line 95, in **init** self.joint_pairs_a, self.joint_pairs_b = joint_pairs_id[:, 0], joint_pairs_id[:, 1] IndexError: too many indices for tensor of dimension 1
> 
> `{ "bone_names": [ "Pelvis", "Spine1", "Spine2", "Spine3", "Neck", "Head", "mixamorig:HeadTop_End", "L_Collar", "L_Shoulder", "L_Elbow", "L_Wrist", "R_Collar", "R_Shoulder", "R_Elbow", "R_Wrist", "L_Hip", "L_Knee", "L_Ankle", "L_Foot", "mixamorig:LeftToe_End", "R_Hip", "R_Knee", "R_Ankle", "R_Foot", "mixamorig:RightToe_End" ], "bone_parents": { "Pelvis": null, "Spine1": "Pelvis", "Spine2": "Spine1", "Spine3": "Spine2", "Neck": "Spine3", "Head": "Neck", "mixamorig:HeadTop_End": "Head", "L_Collar": "Spine3", "L_Shoulder": "L_Collar", "L_Elbow": "L_Shoulder", "L_Wrist": "L_Elbow", "R_Collar": "Spine3", "R_Shoulder": "R_Collar", "R_Elbow": "R_Shoulder", "R_Wrist": "R_Elbow", "L_Hip": "Pelvis", "L_Knee": "L_Hip", "L_Ankle": "L_Knee", "L_Foot": "L_Ankle", "mixamorig:LeftToe_End": "L_Foot", "R_Hip": "Pelvis", "R_Knee": "R_Hip", "R_Ankle": "R_Knee", "R_Foot": "R_Ankle", "mixamorig:RightToe_End": "R_Foot" }, "bone_matrix_rel": "bone_matrix_rel.npy", "bone_matrix_world": "bone_matrix_world.npy", "bone_remap": { "left_ear": null, "right_ear": null, "left_eye": null, "right_eye": null, "head": null, "neck": null, "left_collar": null, "right_collar": null, "left_shoulder": null, "right_shoulder": null, "left_elbow": null, "right_elbow": null, "left_wrist": null, "right_wrist": null, "spine1": null, "spine2": null, "spine3": null, "pelvis": null, "left_hip": null, "right_hip": null, "left_knee": null, "right_knee": null, "left_ankle": null, "right_ankle": null, "left_toe": null, "right_toe": null, "left_index1": null, "left_index2": null, "left_index3": null, "left_index4": null, "left_middle1": null, "left_middle2": null, "left_middle3": null, "left_middle4": null, "left_ring1": null, "left_ring2": null, "left_ring3": null, "left_ring4": null, "left_pinky1": null, "left_pinky2": null, "left_pinky3": null, "left_pinky4": null, "left_thumb1": null, "left_thumb2": null, "left_thumb3": null, "left_thumb4": null, "right_index1": null, "right_index2": null, "right_index3": null, "right_index4": null, "right_middle1": null, "right_middle2": null, "right_middle3": null, "right_middle4": null, "right_ring1": null, "right_ring2": null, "right_ring3": null, "right_ring4": null, "right_pinky1": null, "right_pinky2": null, "right_pinky3": null, "right_pinky4": null, "right_thumb1": null, "right_thumb2": null, "right_thumb3": null, "right_thumb4": null } }`

Hi! Thanks for reporting the problem. It is because bones of your character model skeleton are not named properly. (I am sorry that I did not give details about how to name the bones and name them as what. I will update the document in future), as a result the script can not recogonize any human skeleton bone. 

There are two ways to name your model's bones:

* After exporting skeleton, edit `bone_remap` of `skeleton.json` . Replace "null" to its corresponding bone name of your model. In your case, for example `"head": "Head", "left_shoulder": "R_Shoulder"`. 

* Or just directly edit your model file and rename the bones. To name your bones, open your .blend file, select model skeleton and switch to *pose mode*. You may select bones one by one and rename them in the *property panel*. You can refer to the bone names in keys of "bone_remap".  In your case, for example rename "Head" -> "head", "L_Collar" -> "left_collar", etc.. Then save your blend file (or maybe save a copy if you need it).

I would recommand you edit your model file in a nice GUI. It won't be hard to use blender.
I have a mixamo's robot model renamed properly, but I don't know if it violates the policy to share it on a public link. If you really need it, I may share with you by email :).

**Comment by dustturtle** [comment]
@EasternJournalist would you please send me a mixamo model ? openglnewbee@163.com 
thanks a lot!

**Comment by carryinfo** [comment]
@EasternJournalist 
I meet the same problem, could you share me the mixamo model ?  wxm_linux@163.com
thanks very much

**Comment by Lily19970207** [comment]
@EasternJournalist 
could you share me the model ? llp_199702@163.com  Thanks!

**Comment by EvanJamesMG** [comment]
@EasternJournalist
could you share me the model .   evan123mg@163.com  Thanks!

**Comment by luoww1992** [comment]
@EasternJournalist 
I have the same question,
can you share the model？
luoww1992@sina.com,
thank you !

**Comment by luoww1992** [comment]
@dustturtle,
@carryinfo ,
@EvanJamesMG ,
@Lily19970207 ,

have you get the model ?
你能分享模型吗？
[luoww1992@sina.com](mailto:luoww1992@sina.com)，
谢谢！

**Comment by Guanyuansheng** [comment]
> @dustturtle, @carryinfo , @EvanJamesMG , @Lily19970207 ,
> 
> have you get the model ? 你能分享模型吗？ [luoww1992@sina.com](mailto:luoww1992@sina.com)， 谢谢！

请问您收到模型了吗？
能分享下模型吗，十分感谢！
2111907059@e.gzhu.edu.cn

**Comment by luoww1992** [comment]
@Guanyuansheng 
no model,
i am waitting.....

**Comment by liuhaorandezhanghao** [comment]
could you please tell me where is the file named 'skeleton.json'??

**Comment by liuhaorandezhanghao** [comment]
> Hi, I'd like to try this code，but I got this error. I ran the export_skeleton script and found that bone_remap was none, maybe the character model wasn't adjusted properly, but I'm not familiar with using blender. How should I adjust the character model, or can you send me a character model?
> 
> Export skeleton... Blender 3.2.0 (hash e05e1e369187 built 2022-06-08 11:13:18) Read prefs: C:\Users\ADMIN\AppData\Roaming\Blender Foundation\Blender\3.2\config\userpref.blend Read blend: E:\3Dpose\test_data\characters\hutao.blend bone_matrix_rel float32 (25, 4, 4) True bone_matrix_world float32 (25, 4, 4) True INFO: Created TensorFlow Lite XNNPACK delegate for CPU. Traceback (most recent call last): File "mocap.py", line 125, in main() File "mocap.py", line 60, in main skeleton_ik_solver = SkeletonIKSolver( File "E:\3Dpose\live_mocap\skeleton_ik_solver.py", line 95, in **init** self.joint_pairs_a, self.joint_pairs_b = joint_pairs_id[:, 0], joint_pairs_id[:, 1] IndexError: too many indices for tensor of dimension 1
> 
> `{ "bone_names": [ "Pelvis", "Spine1", "Spine2", "Spine3", "Neck", "Head", "mixamorig:HeadTop_End", "L_Collar", "L_Shoulder", "L_Elbow", "L_Wrist", "R_Collar", "R_Shoulder", "R_Elbow", "R_Wrist", "L_Hip", "L_Knee", "L_Ankle", "L_Foot", "mixamorig:LeftToe_End", "R_Hip", "R_Knee", "R_Ankle", "R_Foot", "mixamorig:RightToe_End" ], "bone_parents": { "Pelvis": null, "Spine1": "Pelvis", "Spine2": "Spine1", "Spine3": "Spine2", "Neck": "Spine3", "Head": "Neck", "mixamorig:HeadTop_End": "Head", "L_Collar": "Spine3", "L_Shoulder": "L_Collar", "L_Elbow": "L_Shoulder", "L_Wrist": "L_Elbow", "R_Collar": "Spine3", "R_Shoulder": "R_Collar", "R_Elbow": "R_Shoulder", "R_Wrist": "R_Elbow", "L_Hip": "Pelvis", "L_Knee": "L_Hip", "L_Ankle": "L_Knee", "L_Foot": "L_Ankle", "mixamorig:LeftToe_End": "L_Foot", "R_Hip": "Pelvis", "R_Knee": "R_Hip", "R_Ankle": "R_Knee", "R_Foot": "R_Ankle", "mixamorig:RightToe_End": "R_Foot" }, "bone_matrix_rel": "bone_matrix_rel.npy", "bone_matrix_world": "bone_matrix_world.npy", "bone_remap": { "left_ear": null, "right_ear": null, "left_eye": null, "right_eye": null, "head": null, "neck": null, "left_collar": null, "right_collar": null, "left_shoulder": null, "right_shoulder": null, "left_elbow": null, "right_elbow": null, "left_wrist": null, "right_wrist": null, "spine1": null, "spine2": null, "spine3": null, "pelvis": null, "left_hip": null, "right_hip": null, "left_knee": null, "right_knee": null, "left_ankle": null, "right_ankle": null, "left_toe": null, "right_toe": null, "left_index1": null, "left_index2": null, "left_index3": null, "left_index4": null, "left_middle1": null, "left_middle2": null, "left_middle3": null, "left_middle4": null, "left_ring1": null, "left_ring2": null, "left_ring3": null, "left_ring4": null, "left_pinky1": null, "left_pinky2": null, "left_pinky3": null, "left_pinky4": null, "left_thumb1": null, "left_thumb2": null, "left_thumb3": null, "left_thumb4": null, "right_index1": null, "right_index2": null, "right_index3": null, "right_index4": null, "right_middle1": null, "right_middle2": null, "right_middle3": null, "right_middle4": null, "right_ring1": null, "right_ring2": null, "right_ring3": null, "right_ring4": null, "right_pinky1": null, "right_pinky2": null, "right_pinky3": null, "right_pinky4": null, "right_thumb1": null, "right_thumb2": null, "right_thumb3": null, "right_thumb4": null } }`

hi , how did you get the file named 'skeleton.json' , i can't generate it .

**Comment by liziwennba** [comment]
@EasternJournalist I've met the same problem, could you share me the model ? liziwennba@gmail.com
Thank you so much

**Comment by siqi0905** [comment]
@dustturtle,
@carryinfo ,
@EvanJamesMG ,
@Lily19970207 ,
@luoww1992,
@EasternJournalist
I also met the same problem, could you share me the model ?

wansiqi4789@mail.ustc.edu.cn
Thanks!

**Comment by liuhaorandezhanghao** [comment]
No method to resolve this problem.
Best wishes 




---- Replied Message ----
| From | ***@***.***> |
| Date | 03/7/2023 17:51 |
| To | ***@***.***> |
| Cc | ***@***.***> ,
***@***.***> |
| Subject | Re: [EasternJournalist/live_mocap] character model wrong (Issue #1) |

@dustturtle,
@carryinfo ,
@EvanJamesMG ,
@Lily19970207 ,
@luoww1992,
@EasternJournalist
I also met the same problem, could you share me the model ?

***@***.***
Thanks!

**Comment by EasternJournalist** [comment]
@dustturtle 
@carryinfo 
@EvanJamesMG 
@liuhaorandezhanghao 
@luoww1992 

Sorry for late response. I was rushing deadlines and course exams in the past months... 
I have sent the models to you all by email. Also I might update the ambiguous description about how to prepare your models soon or later.

**Comment by roberttalling** [comment]
Would also be interested in your rigged model because the instructions are lacking for custom rigs. Could you send your rigged character to me, email  robert.talling@gmail.com. Thank you for great work with the repo!

**Comment by ZhaoXiangXML** [comment]
@EasternJournalist Would you please kindly send me the model file? my email is zhaoxiang-1989 at 126 dot com

**Comment by hahaCrazy** [comment]
Would you please kindly send me the model file? my email is crazyhhhmk@gmail.com

**Comment by sai27** [comment]
could you share me the model . [yubo.net@163.com](mailto:yubo.net@163.com) Thanks!

**Comment by llpspark** [comment]
could you share me the model . [llpspark@163.com]
Thanks!

**Comment by ddv404** [comment]
could you share me the model . ddv888@aliyun.com Thanks!

**Comment by JayL323** [comment]
@EasternJournalist 能把模型分享给我吗？942296928@qq.com
非常感谢！

**Comment by xinhe-github** [comment]
Clould you please also share me the model? [jiangxinhe120@163.com](mailto:jiangxinhe120@163.com) Thanks a lot! @EasternJournalist

**Comment by WZQ1997** [comment]
可以分享下模型吗，谢谢13716031799@163.com

**Comment by yangdot123** [comment]
@dustturtle,
@carryinfo ,
@EvanJamesMG ,
@Lily19970207 ,
@luoww1992,
@EasternJournalist
能分享一下模型吗？谢谢
1106717037@qq.com

**Comment by Brian417-cup** [comment]
能分享一下模型吗，谢谢 985681391@qq.com

**Comment by matlab2017** [comment]
可以分享下模型吗，谢谢 xu1kejie@gmail.com

**Comment by damon-93** [comment]
您好，能分享一下模型吗？952537963@qq.com
